###########
# RTSP
###########

cache=yes
cache-secs=5
cache-pause=yes
cache-pause-initial=no

demuxer-readahead-secs=2
demuxer-max-bytes=128MiB

###########
# 网络
###########

network-timeout=10
stream-lavf-o=rtsp_transport=tcp


###########
# 同步
###########

video-sync=audio
