###########
# RTSP
###########

cache=yes
cache-secs=1
cache-pause=no
cache-pause-initial=no

demuxer-readahead-secs=1
demuxer-max-bytes=64MiB

###########
# 网络
###########

network-timeout=10
stream-lavf-o=rtsp_transport=tcp

###########
# 视频
###########

# hwdec=mediacodec-copy

###########
# 同步
###########

video-sync=display-resample
untimed=no